//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkedIn_Project.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Education
    {
        public int Fk_EducationalOrgId { get; set; }
        public System.Guid Fk_UserId { get; set; }
        public string Grade { get; set; }
        public Nullable<int> Fk_DegreeId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string FieldOfStudy { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Degree Degree { get; set; }
        public virtual EducationalOrg EducationalOrg { get; set; }
    }
}
