//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinkedIn_Project.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Language
    {
        public System.Guid Fk_UserId { get; set; }
        public int Fk_LangId { get; set; }
        public Nullable<int> Fk_LangProficiencyId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual Language Language { get; set; }
        public virtual LanguageProficiency LanguageProficiency { get; set; }
    }
}
